### PR TITLE
Update action to node20

### PR DESCRIPTION
**Pull request by takost**
**Description:**
Node 16 has reached end-of-life on 11 Sep 202.
This PR updates the default runtime to node20, rather then node16.

This is supported on all Actions Runners [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

### CODE REVIEW

**Comment by febuiles** [comment]
@takost Thanks for the PR. This project is old enough to depend on  [node-fetch](https://github.com/actions/go-dependency-submission/blob/main/package-lock.json#L1386), which was superseded by a native `fetch` API in Node 18. This has caused issues with at least [another Action upgrade](https://github.com/actions/dependency-review-action/issues/609).

Do you mind creating a repo showing a successful run of the Action using your branch and then linking it here? I'll see what's up with CI in the meantime.

**Comment by febuiles** [comment]
`npm run all` should fix it, there are some differences in `dist/` I think.

**Comment by takost** [comment]
@febuiles I have created a [repo](https://github.com/takost/go-example) to test action: . My [build](https://github.com/takost/go-example/actions/runs/7061855862/job/19224404206) passes. I am not sure if it is enough to test the action properly. Please help me to test this change.

I am aware of this fetch API change between node versions, but we are going to deprecate Node 16 on our runners in some (near) future. So all `node16`  actions will be forced to run on `node20`. We need to update all first party Github actions to node20, to be able to continue our work, as officially Node16 is out of support since September.

**Review by febuiles — APPROVED** [review]

**Comment by febuiles** [comment]
@takost dependencies were not detected during your run due to the repo being a fork (we don't track those), but everything else looks good so I'm merging!

Do you have a deadline for the Node upgrade? Our team handles a [much more active Action](https://github.com/actions/dependency-review-action) that's still running v16 (cc @jovel) and would also need attention.

**Pull request merged**
